name: nightly

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          pwd
          curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/master/sbt > sbt && chmod 0755 sbt
          ./sbt -Djline.terminal=jline.UnsupportedTerminal scalafmtSbtCheck scalafmtCheck publishM2
      - uses: actions/upload-artifact@v3
        with:
          name: local-m2
          path: /home/runner/.m2/repository

